// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orozokfwspinjfmhnthg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yb3pva2Z3c3BpbmpmbWhudGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTIwMzUsImV4cCI6MjA2NjAyODAzNX0.G2228RE9h8OJ-4ovczkrCmhM-1W8y0lnV0eMQGyJLrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);